'use client';

import React, { useEffect, useState } from 'react';
import { CheckCircle2, FileText, Loader2, Send } from 'lucide-react';
import type { BillingItemType, KraTaxCategory } from '@/lib/etims/tax-engine';

interface Charge {
  code: string;
  name: string;
  item_type: BillingItemType;
  amount: number;
  tax_category: KraTaxCategory;
}

interface AvailableUnit {
  id: string;
  property_name: string;
  unit_number: string;
  tenant_name: string;
  tenant_kra_pin: string | null;
  previous_reading: number;
  charges: Charge[];
}

interface GeneratedInvoice {
  id: string;
  invoice_number: string;
  grand_total: number;
}

interface InvoiceGenerationTabProps {
  role: 'owner' | 'property_manager' | 'caretaker';
}

export function InvoiceGenerationTab({ role }: InvoiceGenerationTabProps) {
  const [units, setUnits] = useState<AvailableUnit[]>([]);
  const [selectedUnitId, setSelectedUnitId] = useState('');
  const [selectedCodes, setSelectedCodes] = useState<string[]>([]);
  const [billingKey, setBillingKey] = useState('rent');
  const [billingMonth, setBillingMonth] = useState(new Date().toISOString().slice(0, 7));
  const [currentReading, setCurrentReading] = useState<number | ''>('');
  const [invoices, setInvoices] = useState<GeneratedInvoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const selectedUnit = units.find((unit) => unit.id === selectedUnitId);
  const selectedCharges = selectedUnit?.charges.filter((charge) => selectedCodes.includes(charge.code)) || [];

  useEffect(() => {
    const loadUnits = async () => {
      try {
        const response = await fetch('/api/invoices/available-units', { cache: 'no-store' });
        const data = await response.json();
        if (!response.ok) throw new Error(data.error || 'Failed to load units');
        setUnits(data.units || []);
        if (data.units?.length) {
          setSelectedUnitId(data.units[0].id);
          setSelectedCodes(data.units[0].charges.filter((charge: Charge) => charge.amount > 0).map((charge: Charge) => charge.code));
        }
      } catch (loadError: unknown) {
        setError(loadError instanceof Error ? loadError.message : 'Failed to load units');
      } finally {
        setLoading(false);
      }
    };
    loadUnits();
  }, []);

  const selectUnit = (unitId: string) => {
    const unit = units.find((candidate) => candidate.id === unitId);
    setSelectedUnitId(unitId);
    setSelectedCodes(unit?.charges.filter((charge) => charge.amount > 0).map((charge) => charge.code) || []);
    setCurrentReading('');
    setMessage(null);
    setError(null);
  };

  const toggleCharge = (code: string) => {
    setSelectedCodes((codes) => codes.includes(code) ? codes.filter((item) => item !== code) : [...codes, code]);
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(null);
    setMessage(null);
    if (!selectedUnit || selectedCharges.length === 0) {
      setError('Select a unit and at least one charge.');
      return;
    }
    const waterCharge = selectedCharges.find((charge) => charge.item_type === 'water_utility');
    if (waterCharge && currentReading !== '' && Number(currentReading) < selectedUnit.previous_reading) {
      setError('Current meter reading cannot be lower than the previous reading.');
      return;
    }

    setSubmitting(true);
    try {
      const response = await fetch('/api/invoices/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          unit_id: selectedUnit.id,
          billing_key: billingKey,
          billing_month: billingMonth,
          items: selectedCharges.map((charge) => ({
            item_type: charge.item_type,
            description: charge.name,
            quantity: 1,
            unit_price: charge.amount,
            override_tax_category: charge.tax_category,
          })),
          previous_reading: selectedUnit.previous_reading,
          current_reading: currentReading === '' ? undefined : Number(currentReading),
          tenant_kra_pin: selectedUnit.tenant_kra_pin,
        }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Failed to generate invoice');
      setInvoices((current) => [data.invoice, ...current]);
      setMessage(`Invoice ${data.invoice.invoice_number} generated by the ${role.replace('_', ' ')}.`);
      setCurrentReading('');
    } catch (submitError: unknown) {
      setError(submitError instanceof Error ? submitError.message : 'Failed to generate invoice');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div className="p-10 flex items-center gap-2 text-gray-500"><Loader2 className="animate-spin" size={20} /> Loading invoice units...</div>;

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
        <div className="flex items-center gap-3 mb-6">
          <FileText className="text-blue-600" size={24} />
          <div><h2 className="text-xl font-bold text-gray-900">Generate Invoice</h2><p className="text-sm text-gray-500">Select the exact charges to include. Each billing scope can be issued once per unit and month.</p></div>
        </div>
        {error && <div className="mb-4 p-3 rounded bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}
        {message && <div className="mb-4 p-3 rounded bg-green-50 border border-green-200 text-green-700 text-sm">{message}</div>}
        {units.length === 0 ? <p className="p-6 bg-gray-50 rounded text-gray-500 text-sm">No occupied units are available for invoicing.</p> : (
          <form onSubmit={handleSubmit} className="space-y-5 max-w-3xl">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <label className="text-sm font-medium text-gray-700">Unit / Tenant<select value={selectedUnitId} onChange={(event) => selectUnit(event.target.value)} className="mt-1 w-full border rounded p-2 bg-white">{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.property_name} - Unit {unit.unit_number} ({unit.tenant_name})</option>)}</select></label>
              <label className="text-sm font-medium text-gray-700">Billing month<input type="month" value={billingMonth} onChange={(event) => setBillingMonth(event.target.value)} className="mt-1 w-full border rounded p-2" /></label>
              <label className="text-sm font-medium text-gray-700">Billing scope<input value={billingKey} onChange={(event) => setBillingKey(event.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, '-'))} className="mt-1 w-full border rounded p-2" placeholder="rent or utilities" /></label>
            </div>
            <div className="border rounded-lg divide-y">
              {selectedUnit?.charges.map((charge) => <label key={charge.code} className="flex items-center justify-between p-3 text-sm"><span className="flex items-center gap-3"><input type="checkbox" checked={selectedCodes.includes(charge.code)} onChange={() => toggleCharge(charge.code)} /><span>{charge.name}</span></span><span className="font-semibold">KES {charge.amount.toLocaleString()}</span></label>)}
            </div>
            {selectedCharges.some((charge) => charge.item_type === 'water_utility') && <div className="grid grid-cols-2 gap-4"><label className="text-sm font-medium text-gray-700">Previous reading<input disabled value={selectedUnit?.previous_reading || 0} className="mt-1 w-full border rounded p-2 bg-gray-50" /></label><label className="text-sm font-medium text-gray-700">Current reading<input type="number" min={selectedUnit?.previous_reading || 0} value={currentReading} onChange={(event) => setCurrentReading(event.target.value ? Number(event.target.value) : '')} className="mt-1 w-full border rounded p-2" /></label></div>}
            <button type="submit" disabled={submitting} className="w-full py-3 rounded bg-blue-600 text-white font-semibold disabled:opacity-50 flex items-center justify-center gap-2"><Send size={18} />{submitting ? 'Generating...' : 'Generate Selected Invoice'}</button>
          </form>
        )}
      </div>
      {invoices.length > 0 && <div className="bg-white border rounded-xl p-5"><h3 className="font-bold mb-3">Invoices generated this session</h3>{invoices.map((invoice) => <div key={invoice.id} className="flex items-center gap-2 text-sm py-2"><CheckCircle2 size={16} className="text-green-600" />{invoice.invoice_number} - KES {Number(invoice.grand_total || 0).toLocaleString()}</div>)}</div>}
    </div>
  );
}
